/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
import sistema.SistemaBiblioteca;
import usuarios.*;


public class TelaLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    
    private SistemaBiblioteca sistema;

    // constantes do admin fixo
    private static final String ADMIN_LOGIN = "bibliotecarioadm";
    private static final String ADMIN_SENHA = "senhabibliotecaadm";
    /**
     * Creates new form inicial
     */
    public TelaLogin(SistemaBiblioteca sistema) {
        this.sistema = sistema;
        initComponents();
        setLocationRelativeTo(null); // centraliza
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ltextoSaudacao = new javax.swing.JLabel();
        textFieldLogin = new javax.swing.JTextField();
        lSenha = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        textFieldSenha = new javax.swing.JTextField();
        botaoEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ltextoSaudacao.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ltextoSaudacao.setText("Bem-vindo(a) ao Sistema de Biblioteca!");

        textFieldLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textFieldLogin.setText("Insira seu login");
        textFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoginActionPerformed(evt);
            }
        });

        lSenha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lSenha.setText("Senha");

        lLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lLogin.setText("Login/Username");

        textFieldSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textFieldSenha.setText("Insira sua senha");
        textFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSenhaActionPerformed(evt);
            }
        });

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ltextoSaudacao)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldLogin))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(lSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldSenha))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(botaoEntrar)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ltextoSaudacao)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLogin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenha)
                    .addComponent(textFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(botaoEntrar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLoginActionPerformed

    private void textFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSenhaActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        String login = textFieldLogin.getText().trim();
        String senha = textFieldSenha.getText().trim();

        // 1) Verifica admin fixo
        if (login.equals(ADMIN_LOGIN) && senha.equals(ADMIN_SENHA)) {
            Admin admin = new Admin("Administrador", "admin@biblioteca.com", login, senha);
            JOptionPane.showMessageDialog(this, "Login como ADMIN.");
            TelaAdmin telaAdmin = new TelaAdmin(sistema, admin);
            telaAdmin.setVisible(true);
            this.dispose();
            return;
        }
        
        // 2) Verifica usuário normal (Aluno ou Professor)
       Usuario u = sistema.validarLogin(login, senha);
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Login ou senha inválidos.");
            return;
        }

        JOptionPane.showMessageDialog(this,
        "Login como " + u.getClass().getSimpleName() + " - " + u.getNome());

        TelaUsuario telaUsuario = new TelaUsuario(sistema, u);
        telaUsuario.setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_botaoEntrarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SistemaBiblioteca sistema = new SistemaBiblioteca();
        java.awt.EventQueue.invokeLater(() -> new TelaLogin(sistema).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel ltextoSaudacao;
    private javax.swing.JTextField textFieldLogin;
    private javax.swing.JTextField textFieldSenha;
    // End of variables declaration//GEN-END:variables
}
