/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import javax.swing.JOptionPane;
import sistema.Livro;
import sistema.SistemaBiblioteca;
import usuarios.*;
import sistema.Emprestimo;

/**
 *
 * @author julia
 */
public class TelaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdmin.class.getName());

    private SistemaBiblioteca sistema;
    private Admin admin;
    
    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin(SistemaBiblioteca sistema, Admin admin) {
        this.sistema = sistema;
        this.admin = admin;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lBemVindo = new javax.swing.JLabel();
        btnCadastrarLivro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarAluno = new javax.swing.JButton();
        btnCadastrarProf = new javax.swing.JButton();
        btnListarLivros = new javax.swing.JButton();
        btnListarUsers = new javax.swing.JButton();
        btnListarEmprest = new javax.swing.JButton();
        btnAprovarEmprest = new javax.swing.JButton();
        btnRegistrarDev = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lBemVindo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lBemVindo.setText("Bem-vindo, Bibliotecário!");

        btnCadastrarLivro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCadastrarLivro.setText("Cadastrar Livro");
        btnCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Escolha uma ação:");

        btnCadastrarAluno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCadastrarAluno.setText("Cadastrar Aluno");
        btnCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlunoActionPerformed(evt);
            }
        });

        btnCadastrarProf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCadastrarProf.setText("Cadastrar Professor");
        btnCadastrarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProfActionPerformed(evt);
            }
        });

        btnListarLivros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarLivros.setText("Listar Livros");
        btnListarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivrosActionPerformed(evt);
            }
        });

        btnListarUsers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarUsers.setText("Listar Usuários");

        btnListarEmprest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarEmprest.setText("Listar Empréstimos");

        btnAprovarEmprest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAprovarEmprest.setText("Aprovar Empréstimo");
        btnAprovarEmprest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarEmprestActionPerformed(evt);
            }
        });

        btnRegistrarDev.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegistrarDev.setText("Registrar Devolução");

        btnSair.setBackground(new java.awt.Color(255, 204, 204));
        btnSair.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSair.setText("Sair/Log out");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnListarLivros)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnListarUsers)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnListarEmprest))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCadastrarLivro)
                                            .addGap(12, 12, 12)
                                            .addComponent(btnCadastrarAluno)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCadastrarProf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAprovarEmprest)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrarDev)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarLivro)
                    .addComponent(btnCadastrarAluno)
                    .addComponent(btnCadastrarProf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarLivros)
                    .addComponent(btnListarUsers)
                    .addComponent(btnListarEmprest))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprovarEmprest)
                    .addComponent(btnRegistrarDev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivroActionPerformed
        String titulo = JOptionPane.showInputDialog(this, "Título do livro:");
        if (titulo == null || titulo.isBlank()) {
            return;
        }

        String autor = JOptionPane.showInputDialog(this, "Autor do livro:");
        if (autor == null || autor.isBlank()) {
            return;
        }

        String isbnStr = JOptionPane.showInputDialog(this, "ISBN (número):");
        if (isbnStr == null) {
            return;
        }

        try {
            int isbn = Integer.parseInt(isbnStr);
            Livro livro = new Livro(titulo, autor, isbn, true);
            admin.cadastrarLivro(sistema, livro); // usa Admin chamando SistemaBiblioteca
            JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ISBN inválido.");
        }

    }//GEN-LAST:event_btnCadastrarLivroActionPerformed

    private void btnListarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivrosActionPerformed
        StringBuilder sb = new StringBuilder("Livros cadastrados:\n\n");
        for (Livro l : sistema.listarLivros()) {
            sb.append(l).append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_btnListarLivrosActionPerformed

    private void btnCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunoActionPerformed
        String nome = JOptionPane.showInputDialog(this, "Nome do aluno:");
        if (nome == null || nome.isBlank()) {
            return;
        }

        String email = JOptionPane.showInputDialog(this, "Email:");
        if (email == null) {
            return;
        }

        String login = JOptionPane.showInputDialog(this, "Login:");
        if (login == null) {
            return;
        }

        String senha = JOptionPane.showInputDialog(this, "Senha:");
        if (senha == null) {
            return;
        }

        String matriculaStr = JOptionPane.showInputDialog(this, "Matrícula:");
        if (matriculaStr == null) {
            return;
        }

        String curso = JOptionPane.showInputDialog(this, "Curso:");
        if (curso == null) {
            return;
        }

        String periodoStr = JOptionPane.showInputDialog(this, "Período:");
        if (periodoStr == null) {
            return;
        }

        try {
            int matricula = Integer.parseInt(matriculaStr);
            int periodo = Integer.parseInt(periodoStr);

            Aluno aluno = new Aluno(nome, email, login, senha, matricula, curso, periodo);
            sistema.adicionarUsuario(aluno);
            JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Matrícula ou período inválidos.");
        }
    }//GEN-LAST:event_btnCadastrarAlunoActionPerformed

    private void btnCadastrarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProfActionPerformed
        String nome = JOptionPane.showInputDialog(this, "Nome do professor:");
        if (nome == null || nome.isBlank()) {
            return;
        }

        String email = JOptionPane.showInputDialog(this, "Email:");
        if (email == null) {
            return;
        }

        String login = JOptionPane.showInputDialog(this, "Login:");
        if (login == null) {
            return;
        }

        String senha = JOptionPane.showInputDialog(this, "Senha:");
        if (senha == null) {
            return;
        }

        String matriculaStr = JOptionPane.showInputDialog(this, "Matrícula:");
        if (matriculaStr == null) {
            return;
        }

        try {
            int matricula = Integer.parseInt(matriculaStr);
            Professor p = new Professor(nome, email, login, senha, matricula);
            sistema.adicionarUsuario(p);
            JOptionPane.showMessageDialog(this, "Professor cadastrado com sucesso!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Matrícula inválida.");
        }
    }//GEN-LAST:event_btnCadastrarProfActionPerformed

    private void btnAprovarEmprestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarEmprestActionPerformed
        java.util.List<Emprestimo> pendentes = new java.util.ArrayList<>();
        for (Emprestimo e : sistema.listarEmprestimos()) {
            if ("PENDENTE".equals(e.getStatus())) {
                pendentes.add(e);
            }
        }
        if (pendentes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há empréstimos pendentes.");
            return;
        }

        String[] opcoes = new String[pendentes.size()];
        for (int i = 0; i < pendentes.size(); i++) {
            opcoes[i] = (i + 1) + " - " + pendentes.get(i).toString();
        }

        String escolha = (String) JOptionPane.showInputDialog(
                this,
                "Selecione um empréstimo para aprovar:",
                "Aprovar Empréstimo",
                JOptionPane.PLAIN_MESSAGE,
                null,
                opcoes,
                opcoes[0]
        );

        if (escolha == null) {
            return;
        }

        int indice = Integer.parseInt(escolha.split(" ")[0]) - 1;
        Emprestimo selecionado = pendentes.get(indice);

        try {
            sistema.aprovarEmprestimo(selecionado);
            JOptionPane.showMessageDialog(this, "Empréstimo aprovado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao aprovar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAprovarEmprestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        SistemaBiblioteca sistema = new SistemaBiblioteca();
        Admin admin = new Admin();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdmin(sistema, admin).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprovarEmprest;
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnCadastrarLivro;
    private javax.swing.JButton btnCadastrarProf;
    private javax.swing.JButton btnListarEmprest;
    private javax.swing.JButton btnListarLivros;
    private javax.swing.JButton btnListarUsers;
    private javax.swing.JButton btnRegistrarDev;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lBemVindo;
    // End of variables declaration//GEN-END:variables
}
