/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import javax.swing.JOptionPane;
import sistema.Emprestimo;
import sistema.Livro;
import sistema.SistemaBiblioteca;
import usuarios.*;

/**
 *
 * @author julia
 */
public class TelaUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaUsuario.class.getName());
    private SistemaBiblioteca sistema;
    private Usuario usuario;
    
    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario(SistemaBiblioteca sistema) {
        this.sistema = sistema;
        initComponents();
        setLocationRelativeTo(null);
        lBemVindoUser.setText("Bem-vindo, " + usuario.getNome() + " (" + usuario.getClass().getSimpleName() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lBemVindoUser = new javax.swing.JLabel();
        btnListarLivrosUser = new javax.swing.JButton();
        btnSolicitarEmpres = new javax.swing.JButton();
        btnListarEmpresUser = new javax.swing.JButton();
        btnSairUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lBemVindoUser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lBemVindoUser.setText("Bem-vindo! Escolha uma opção:");

        btnListarLivrosUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarLivrosUser.setText("Listar Livros");
        btnListarLivrosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivrosUserActionPerformed(evt);
            }
        });

        btnSolicitarEmpres.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSolicitarEmpres.setText("Solicitar Empréstimo");
        btnSolicitarEmpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarEmpresActionPerformed(evt);
            }
        });

        btnListarEmpresUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarEmpresUser.setText("Meus Empréstimos");
        btnListarEmpresUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEmpresUserActionPerformed(evt);
            }
        });

        btnSairUser.setBackground(new java.awt.Color(255, 204, 204));
        btnSairUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairUser.setText("Sair/Log out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSairUser)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarLivrosUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSolicitarEmpres))
                    .addComponent(lBemVindoUser, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnListarEmpresUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lBemVindoUser)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarLivrosUser)
                    .addComponent(btnSolicitarEmpres))
                .addGap(30, 30, 30)
                .addComponent(btnListarEmpresUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnSairUser)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLivrosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivrosUserActionPerformed
        StringBuilder sb = new StringBuilder("Livros disponíveis:\n\n");
        for (Livro l : sistema.listarLivros()) {
            sb.append(l).append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_btnListarLivrosUserActionPerformed

    private void btnSolicitarEmpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarEmpresActionPerformed
        String isbnStr = JOptionPane.showInputDialog(this, "Informe o ISBN do livro:");
        if (isbnStr == null) {
            return;
        }

        try {
            int isbn = Integer.parseInt(isbnStr);
            Emprestimo e = sistema.solicitarEmprestimo(usuario, isbn);
            JOptionPane.showMessageDialog(this, "Empréstimo solicitado. Status: " + e.getStatus());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ISBN inválido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSolicitarEmpresActionPerformed

    private void btnListarEmpresUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEmpresUserActionPerformed
        StringBuilder sb = new StringBuilder("Meus empréstimos:\n\n");
        for (Emprestimo e : sistema.listarEmprestimos()) {
            if (e.getUsuario().equals(usuario)) {
                sb.append(e).append("\n");
            }
        }
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_btnListarEmpresUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        SistemaBiblioteca sistema = new SistemaBiblioteca();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaUsuario(sistema).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarEmpresUser;
    private javax.swing.JButton btnListarLivrosUser;
    private javax.swing.JButton btnSairUser;
    private javax.swing.JButton btnSolicitarEmpres;
    private javax.swing.JLabel lBemVindoUser;
    // End of variables declaration//GEN-END:variables
}
