/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import javax.swing.JOptionPane;
import sistema.Emprestimo;
import sistema.Livro;
import sistema.SistemaBiblioteca;
import usuarios.*;


public class TelaUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName());

    private final SistemaBiblioteca sistema;
    private final Usuario usuario;   
    
    public TelaUsuario(SistemaBiblioteca sistema, Usuario usuario) {
        this.sistema = sistema;
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        String tipo;
        if (usuario instanceof Aluno) {
            tipo = "Aluno";
        } else if (usuario instanceof Professor) {
            tipo = "Professor";
        } else {
            tipo = "Usuário";
        }
        lBemVindoUser.setText(
            "Bem-vindo, " + usuario.getNome() + " (" + tipo + ")"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lBemVindoUser = new javax.swing.JLabel();
        btnListarLivrosUser = new javax.swing.JButton();
        btnSolicitarEmpres = new javax.swing.JButton();
        btnListarEmpresUser = new javax.swing.JButton();
        btnSairUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lBemVindoUser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lBemVindoUser.setText("Bem-vindo! Escolha uma opção:");

        btnListarLivrosUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarLivrosUser.setText("Listar Livros");
        btnListarLivrosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivrosUserActionPerformed(evt);
            }
        });

        btnSolicitarEmpres.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSolicitarEmpres.setText("Solicitar Empréstimo");
        btnSolicitarEmpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarEmpresActionPerformed(evt);
            }
        });

        btnListarEmpresUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarEmpresUser.setText("Meus Empréstimos");
        btnListarEmpresUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEmpresUserActionPerformed(evt);
            }
        });

        btnSairUser.setBackground(new java.awt.Color(255, 204, 204));
        btnSairUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairUser.setText("Sair/Log out");
        btnSairUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSairUser)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarLivrosUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSolicitarEmpres))
                    .addComponent(lBemVindoUser, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnListarEmpresUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lBemVindoUser)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarLivrosUser)
                    .addComponent(btnSolicitarEmpres))
                .addGap(30, 30, 30)
                .addComponent(btnListarEmpresUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnSairUser)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnListarLivrosUserActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        StringBuilder sb = new StringBuilder("Livros disponíveis:\n\n");
        for (Livro l : sistema.listarLivros()) {
            sb.append(l).append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString());
    }                                                   

    private void btnSolicitarEmpresActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String isbnStr = JOptionPane.showInputDialog(this, "Informe o ISBN do livro:");
        if (isbnStr == null) {
            return;
        }

        try {
            int isbn = Integer.parseInt(isbnStr);
            Emprestimo e = sistema.solicitarEmprestimo(usuario, isbn);
            JOptionPane.showMessageDialog(this, "Empréstimo solicitado. Status: " + e.getStatus());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ISBN inválido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }                                                  

    private void btnListarEmpresUserActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        StringBuilder sb = new StringBuilder("Meus empréstimos:\n\n");
    
        boolean temAlgum = false;

        for (Emprestimo e : sistema.listarEmprestimos()) {
            if (e.getUsuario().equals(usuario)) {
                temAlgum = true;
                sb.append(e.toString());
                sb.append("\n");


                if (e.emAtraso()) {
                    double multa = e.calcularMulta();
                    sb.append("   EM ATRASO! Multa atual: R$ ")
                    .append(String.format("%.2f", multa))
                    .append("\n");
                } else if ("APROVADO".equals(e.getStatus())) {
                    sb.append("   Ainda dentro do prazo.\n");
                }

            sb.append("\n");
            }
        }

        if (!temAlgum) {
            sb.append("Você não possui empréstimos.");
        }

        JOptionPane.showMessageDialog(this, sb.toString());
    }                                                   

    private void btnSairUserActionPerformed(java.awt.event.ActionEvent evt) {                                            
        sistema.salvarTudo();
        new TelaLogin(sistema).setVisible(true);
        this.dispose();
    }                                           

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnListarEmpresUser;
    private javax.swing.JButton btnListarLivrosUser;
    private javax.swing.JButton btnSairUser;
    private javax.swing.JButton btnSolicitarEmpres;
    private javax.swing.JLabel lBemVindoUser;
    // End of variables declaration                   
}
